name: Dependabot auto-manage
on: pull_request

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'ad/telegram-busy-buttons'
    env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          gh-version: latest
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Ensure "production" label exists
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: |
          set -euo pipefail
          NAME=$(gh label list --repo "$GITHUB_REPOSITORY" --limit 1000 --json name --jq '.[] | select(.name=="production") | .name')
          if [ -z "$NAME" ]; then
            gh label create "production" --repo "$GITHUB_REPOSITORY" --color "0E8A16" --description "Auto-approved Dependabot PRs ready for production"
          fi

      - name: Add "production" label
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr edit "${{ github.event.pull_request.html_url }}" --add-label "production"

      - name: Approve PR
        run: gh pr review --repo "${{ github.repository }}" --approve "${{ github.event.pull_request.number }}"

      - name: Auto-merge PR
        run: gh pr merge --repo "${{ github.repository }}" --rebase --auto "${{ github.event.pull_request.number }}"
