name: Dependabot auto-manage
on: 
  pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to process'
        required: true
        type: number

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    # if: |
    #   (github.event_name == 'pull_request' && github.event.pull_request.user.login == 'dependabot[bot]' && github.repository == 'ad/telegram-busy-buttons') ||
    #   (github.event_name == 'workflow_dispatch')
    env:
        GH_TOKEN: ${{ github.token }}
        PR_NUMBER: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number || github.event.pull_request.number }}
        PR_URL: ${{ github.event_name == 'workflow_dispatch' && format('https://github.com/{0}/pull/{1}', github.repository, github.event.inputs.pr_number) || github.event.pull_request.html_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2

      - name: Ensure "production" label exists
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -euo pipefail
          NAME=$(gh label list --repo "${{ github.repository }}" --limit 1000 --json name --jq '.[] | select(.name=="production") | .name')
          if [ -z "$NAME" ]; then
            gh label create "production" --repo "${{ github.repository }}" --color "0E8A16" --description "Auto-approved Dependabot PRs ready for production"
          fi

      - name: Add "production" label
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr edit "${{ env.PR_URL }}" --add-label "production"

      - name: Approve PR (production dependencies only)
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr review --repo "${{ github.repository }}" --approve "${{ env.PR_NUMBER }}"

      - name: Auto-merge PR (production dependencies only)
        if: steps.metadata.outputs.dependency-type == 'direct:production'
        run: gh pr merge --repo "${{ github.repository }}" --squash --auto "${{ env.PR_NUMBER }}"
